"""
Detection signals for Provenance Guard.

M3 scope: Signal 1 only — LLM-based AI/human classification via Groq.
Test standalone with: python -c "from signals import llm_detector; print(llm_detector('...'))"
"""

import logging
import os
import re
import statistics

from dotenv import load_dotenv
from groq import Groq

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

# Load variables from .env into os.environ (e.g. GROQ_API_KEY).
# load_dotenv() looks for a .env file in the current working directory.
load_dotenv()

logger = logging.getLogger(__name__)

# Groq model from planning.md — good balance of speed and classification quality.
GROQ_MODEL = "llama-3.3-70b-versatile"

# Fallback score when the model returns something we cannot parse after one retry.
# 0.5 lands in the "Uncertain" band (0.30 < confidence < 0.70) in planning.md,
# which is honest: we genuinely don't know if the parse failed.
DEFAULT_LLM_SCORE = 0.5

# Prompt instructs the model to return ONLY a numeric probability.
_CLASSIFICATION_PROMPT = """\
You are an expert at distinguishing human-written text from AI-generated text.

Read the following text and assess whether it was written by a human or generated by AI.

Respond with ONLY a single decimal number between 0 and 1:
- 1.0 means you are certain the text is AI-generated
- 0.0 means you are certain the text is human-written
- Values in between represent your degree of confidence that it is AI-generated

Do not include any other words, punctuation, or explanation — just the number.

TEXT TO CLASSIFY:
{text}"""


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _get_groq_client() -> Groq:
    """Build a Groq client using the API key from the environment."""
    api_key = os.getenv("GROQ_API_KEY")
    if not api_key:
        raise ValueError(
            "GROQ_API_KEY is not set. Add it to your .env file "
            "(see https://console.groq.com/keys)."
        )
    return Groq(api_key=api_key)


def _call_groq(text: str) -> str:
    """
    Send text to Groq and return the model's raw response string.

    Uses chat.completions.create — the standard Groq chat API.
    temperature=0 keeps responses more deterministic for numeric output.
    """
    client = _get_groq_client()

    response = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[
            {
                "role": "user",
                "content": _CLASSIFICATION_PROMPT.format(text=text),
            }
        ],
        temperature=0,
        max_tokens=16,  # We only need a short number like "0.73"
    )

    # choices[0] is the first (and usually only) completion candidate.
    return response.choices[0].message.content.strip()


def _parse_probability(raw: str) -> float:
    """
    Extract a float in [0, 1] from the model's response.

    The model is asked for a clean number, but may add extra text anyway
    (e.g. "0.85" or "The score is 0.85"). We use regex to find the first
    number that looks like a probability.

    Raises ValueError if no valid number can be found.
    """
    # Find all number-like tokens (0.5, .75, 1, 0, etc.) and pick the first in [0, 1].
    candidates = re.findall(r"\d*\.\d+|\d+", raw)
    if not candidates:
        raise ValueError(f"No numeric value found in model response: {raw!r}")

    for token in candidates:
        value = float(token)
        if 0.0 <= value <= 1.0:
            return value

    raise ValueError(
        f"No value in [0, 1] found in model response: {raw!r} (candidates: {candidates})"
    )


def _score_with_retry(text: str) -> float:
    """
    Call Groq once; if parsing fails, retry the API call one more time.

    Returns the parsed probability, or raises ValueError if both attempts fail.
    """
    last_error: Exception | None = None

    for attempt in range(2):
        raw = _call_groq(text)
        try:
            return _parse_probability(raw)
        except ValueError as exc:
            last_error = exc
            logger.warning(
                "Attempt %d: could not parse Groq response %r — %s",
                attempt + 1,
                raw,
                exc,
            )

    # Both attempts failed to produce a parseable number.
    raise ValueError(f"Failed to parse model response after 2 attempts: {last_error}")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def llm_detector(text: str) -> float:
    """
    Signal 1: classify text as AI-generated using Groq's LLM.

    Args:
        text: The content to analyze.

    Returns:
        Float in [0, 1] — probability the text is AI-generated
        (1.0 = definitely AI, 0.0 = definitely human).

    If the model returns an unparseable response twice, returns DEFAULT_LLM_SCORE
    (0.5 = uncertain) and logs a warning so the failure is visible, not silent.
    """
    try:
        return _score_with_retry(text)
    except ValueError:
        logger.warning(
            "llm_detector falling back to DEFAULT_LLM_SCORE=%s "
            "(model did not return a clean number after retry)",
            DEFAULT_LLM_SCORE,
        )
        return DEFAULT_LLM_SCORE


def stylometry_signal(text: str) -> float:
    """
    Signal 2: structural AI-likelihood from sentence variance and vocabulary diversity.

    Returns a float in [0, 1] where higher = more AI-like (same scale as llm_detector).
    """
    # Edge case: no analyzable words (empty/whitespace-only). We can't measure
    # structure, so return 0.5 (neutral / uncertain) rather than crashing.
    words = re.findall(r"\b\w+\b", text.lower())
    if not words:
        return 0.5

    # --- Metric 2: type-token ratio (TTR) ---
    ttr = len(set(words)) / len(words)
    # Invert: rich vocabulary (high TTR, human-like) → low AI signal.
    ttr_signal = 1.0 - ttr

    # --- Metric 1: sentence length variation (coefficient of variation) ---
    # Split on sentence-ending punctuation (. ! ?). Imperfect but sufficient here.
    raw_sentences = re.split(r"[.!?]+", text)
    sentences = [s.strip() for s in raw_sentences if s.strip()]

    # Word count per sentence (reuse the same word tokenizer as TTR).
    sentence_lengths = [len(re.findall(r"\b\w+\b", s.lower())) for s in sentences]
    sentence_lengths = [n for n in sentence_lengths if n > 0]

    # Fewer than 2 measurable sentences means we can't assess rhythm (no punctuation
    # or only one sentence). Don't invent a variance of 0 — use TTR alone instead.
    if len(sentence_lengths) < 2:
        return ttr_signal

    # Coefficient of variation (stdev / mean) normalizes for naturally long or
    # short sentences, unlike raw variance on word counts.
    mean_length = statistics.mean(sentence_lengths)
    cv = statistics.stdev(sentence_lengths) / mean_length
    normalized_cv = min(cv / 0.8, 1.0)
    # Invert: high variation in rhythm (human-like) → low AI signal.
    variance_signal = 1.0 - normalized_cv

    # Average both structural signals when sentence rhythm is measurable.
    return (variance_signal + ttr_signal) / 2
